development:
  adapter: mysql2
  database: sampleapp_development
  username: root
  password:
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  database: sampleapp_test
  username: root
  password:
  host: 127.0.0.1
  port: 3306

# staging:
#   adapter: mysql2
#   database: sampleapp_staging
#   username: staging
#   password: e2ek.4:9
#   host: 10.0.4.155 # db.tick.staging2.molehill.managedmachine.com
#   port: 3306
#
# production:
#   adapter: mysql2
#   database: sampleapp_production
#   username: production
#   password: e2ek.4:9
#   host: 10.0.3.5 #db1.tick.molehill.managedmachine.com
#   port: 3306
