# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40d93c6642f214688c6bd8e0c72ba6155a0549683bdc917f91241a621c3191927b77bc00bb32a878ee9d34d906da6917cd97c5fc23037ecf6888ce1296f6657e

test:
  secret_key_base: 119a4335929aa8dfb427a251daf18b59eef78ccd86396e5c5a1c01ee4d9c67dedd0188061a2a68ed1388027467f9036eaab99192c9af9adcf5ecb9e63baa0ce2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
